baseURL = "https://mayukhdeb.github.io/notes/"
title = "Notes"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
publishDir = "docs"

[author]
  name = ""
  abstract = "This is a place to keep my notes, mostly from the papers I read and find interesting."

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
